language: java
jdk:
- oraclejdk8
script:
- "./gradlew assemble test"
before_install:
- openssl aes-256-cbc -K $encrypted_96717127ae4b_key -iv $encrypted_96717127ae4b_iv
  -in credentials.yml.enc -out spring-security-saml-dsl/src/test/resources/credentials.yml
  -d
addons:
  firefox: '45.0'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3